name: Fetch Appstore Info 

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Append to Gist
        uses: andymckay/append-gist-action@0.1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gistURL: "https://gist.github.com/techinpark/abc051d2bc6bb03d3365d86aac597dca" 
          file: store.db
